version: 2

before:
  hooks:
    - go mod tidy
    - "sed -i.bak 's/\"version\": \".*\"/\"version\": \"{{ .Version }}\"/' plugin.json && rm -f plugin.json.bak"

builds:
  - skip: true

changelog:
  sort: asc
