// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/ws_auth.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HMACAuthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharedSecret  string                 `protobuf:"bytes,1,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HMACAuthConfig) Reset() {
	*x = HMACAuthConfig{}
	mi := &file_internal_contracts_ws_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HMACAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMACAuthConfig) ProtoMessage() {}

func (x *HMACAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ws_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMACAuthConfig.ProtoReflect.Descriptor instead.
func (*HMACAuthConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ws_auth_proto_rawDescGZIP(), []int{0}
}

func (x *HMACAuthConfig) GetSharedSecret() string {
	if x != nil {
		return x.SharedSecret
	}
	return ""
}

func (x *HMACAuthConfig) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type AuthIdentityConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthIdentityConfig) Reset() {
	*x = AuthIdentityConfig{}
	mi := &file_internal_contracts_ws_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthIdentityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthIdentityConfig) ProtoMessage() {}

func (x *AuthIdentityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ws_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthIdentityConfig.ProtoReflect.Descriptor instead.
func (*AuthIdentityConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ws_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthIdentityConfig) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type AuthIdentityInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthIdentityInput) Reset() {
	*x = AuthIdentityInput{}
	mi := &file_internal_contracts_ws_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthIdentityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthIdentityInput) ProtoMessage() {}

func (x *AuthIdentityInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ws_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthIdentityInput.ProtoReflect.Descriptor instead.
func (*AuthIdentityInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ws_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthIdentityInput) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type AuthIdentityOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Authenticated bool                   `protobuf:"varint,2,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthIdentityOutput) Reset() {
	*x = AuthIdentityOutput{}
	mi := &file_internal_contracts_ws_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthIdentityOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthIdentityOutput) ProtoMessage() {}

func (x *AuthIdentityOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ws_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthIdentityOutput.ProtoReflect.Descriptor instead.
func (*AuthIdentityOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ws_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthIdentityOutput) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *AuthIdentityOutput) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthIdentityOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_ws_auth_proto protoreflect.FileDescriptor

const file_internal_contracts_ws_auth_proto_rawDesc = "" +
	"\n" +
	" internal/contracts/ws_auth.proto\x12\x1bworkflow.plugins.ws_auth.v1\"R\n" +
	"\x0eHMACAuthConfig\x12#\n" +
	"\rshared_secret\x18\x01 \x01(\tR\fsharedSecret\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"9\n" +
	"\x12AuthIdentityConfig\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"8\n" +
	"\x11AuthIdentityInput\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"m\n" +
	"\x12AuthIdentityOutput\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12$\n" +
	"\rauthenticated\x18\x02 \x01(\bR\rauthenticated\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBCZAgithub.com/GoCodeAlone/workflow-plugin-ws-auth/internal/contractsb\x06proto3"

var (
	file_internal_contracts_ws_auth_proto_rawDescOnce sync.Once
	file_internal_contracts_ws_auth_proto_rawDescData []byte
)

func file_internal_contracts_ws_auth_proto_rawDescGZIP() []byte {
	file_internal_contracts_ws_auth_proto_rawDescOnce.Do(func() {
		file_internal_contracts_ws_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_ws_auth_proto_rawDesc), len(file_internal_contracts_ws_auth_proto_rawDesc)))
	})
	return file_internal_contracts_ws_auth_proto_rawDescData
}

var file_internal_contracts_ws_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_contracts_ws_auth_proto_goTypes = []any{
	(*HMACAuthConfig)(nil),     // 0: workflow.plugins.ws_auth.v1.HMACAuthConfig
	(*AuthIdentityConfig)(nil), // 1: workflow.plugins.ws_auth.v1.AuthIdentityConfig
	(*AuthIdentityInput)(nil),  // 2: workflow.plugins.ws_auth.v1.AuthIdentityInput
	(*AuthIdentityOutput)(nil), // 3: workflow.plugins.ws_auth.v1.AuthIdentityOutput
}
var file_internal_contracts_ws_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_contracts_ws_auth_proto_init() }
func file_internal_contracts_ws_auth_proto_init() {
	if File_internal_contracts_ws_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_ws_auth_proto_rawDesc), len(file_internal_contracts_ws_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_ws_auth_proto_goTypes,
		DependencyIndexes: file_internal_contracts_ws_auth_proto_depIdxs,
		MessageInfos:      file_internal_contracts_ws_auth_proto_msgTypes,
	}.Build()
	File_internal_contracts_ws_auth_proto = out.File
	file_internal_contracts_ws_auth_proto_goTypes = nil
	file_internal_contracts_ws_auth_proto_depIdxs = nil
}
